### ISSUE TITLE
Some windows don't get assigned names

### ISSUE THREAD

**Issue by ctSkennerton** [wwood/bioruby-kmer_counter#1]
I noticed this weird thing today that some of the windows don't get assigned a name.  I can't seem to find a pattern for this, it's only in a very small number of windows.  I ran the code with the default settings and you can find the input file `combined_contigs_gt_50kb.fa` in my home directory

**Comment by wwood** [comment]
I've been unable to confirm this, do you have a line number or example of a 'missing name' please?

``` sh
$ awk '{print $1}' combined_contigs_gt_50kb.fa.kmers.csv |grep -ve 'Combined_contig_[0-9]' |head
ID
```

**Comment by ctSkennerton** [comment]
In the output barcodes file at line 8042, 8048, 1478, 7099.  Plus there are a few others around the 8000 mark

**Comment by wwood** [comment]
Still not seeing it: my output was `combined_contigs_gt_50kb.fa.kmers.csv` in my home dir - any `diff`?

`which kmer_counter.rb`?

**Comment by wwood** [comment]
gimme a sec it is still copying across..

**Comment by wwood** [comment]
ok, copying complete. Thanks

**Comment by ctSkennerton** [comment]
I re-ran it again on the file, there are some differences but I don't think that they are significant - just ruby rounding errors.  But other than that all of the headers are in place.  I don't know what happened to that other file, cause nothing has touched it.  Oh well, false alarm maybe

**Comment by wwood** [comment]
No worries - it alerted me to another bug (that doesn't affect the output,
just a ui thing), anyway. So I'll release 0.0.3.

**Comment by wwood** [comment]
And it turns out the original bug was actually a bug, introduced by using multiple processes, where each is able to print to the screen. How dumb is the author! Multiple processes are no longer used, ever, as a consequence.
